export type TenantType = {
  id: number;
  name: string;
  email: string;
  avatar: string | null;
  email_verified_at: string | null;
  balance: string;
  created_at: string;
  updated_at: string;
  avatar_url: string | null;
  tenant_profile: {
    id: number;
    user_id: number;
    type: string;
    alt_phone_number: string | null;
    nationality: string;
    identity_number: string;
    race: string;
    gender: string;
    address_line_1: string;
    city: string;
    postcode: string;
    state: string;
    country: string;
    emergency_name: string;
    emergency_relationship: string;
    emergency_phone: string | null;
    emergency_email: string | null;
    remarks: string | null;
    created_at: string;
    updated_at: string;
  };
};
