import EquipmentType from "./EquipmentType";
import LockType from "./LockType";
import MeterType from "./MeterType";
import PropertySettingType from "./PropertySetting";
import { Property } from "./PropertyType";
import { Room } from "./RoomType";
import { Tenancy } from "./TenancyType";

export type Unit = {
  id: number;
  property_id: number;
  beneficiary_id: number;
  block: string;
  status: string;
  floor: string;
  unit_number: string;
  block_floor_unit_number: string;
  rental_type: "Whole Unit" | "Room Rental";
  bedroom_count: number;
  bathroom_count: number;
  square_feet: number | null;
  unit_image: string | null;
  floor_plan_image: string | null;
  floor_plan_image_url: string;
  description: string;
  remarks: string;
  access_card_numbers: string[];
  is_activated: number;
  service_fee_percentage: string;
  profit_sharing_percentage: string;
  last_active_tenancy: Tenancy[];
  created_at: string;
  updated_at: string;
  meters: MeterType[];
  locks: LockType[];
  rooms: Room[];
  carparks: Carpark[];
  equipment?: EquipmentType[];
  setting?: PropertySettingType;
  property: Property;
};
