type Unit = {
  id: number;
  property_id: number;
  beneficiary_id: number;
  block: string;
  floor: string;
  unit_number: string;
  block_floor_unit_number: string;
  rental_type: "Whole Unit" | "Sublet";
  bedroom_count: number;
  bathroom_count: number;
  square_feet: number | null;
  unit_image: string | null;
  floor_plan_image: string | null;
  description: string;
  remarks: string;
  access_card_numbers: string[];
  is_activated: number;
  service_fee_percentage: string;
  profit_sharing_percentage: string;
  created_at: string;
  updated_at: string;
  meters: Meter[];
  locks: Locks[];
  rooms: Room[];
  carparks: Carpark[];
  property: Property;
};
