import { useMutation, useQueryClient } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";
import { toast } from "sonner";
// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddPropertyInput = Omit<
  Property,
  "id" | "created_at" | "updated_at" | "created_by"
>;

const useAddProperty = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationKey: ["AddProperty"],
    mutationFn: async (newProperty: object) => {
      const res = await axiosInstance.post<Property>(
        "/properties",
        newProperty
      );
      return res.data;
    },
    onSuccess: () => {
      // Invalidate and refetch units list
      queryClient.invalidateQueries({ queryKey: ["GetPropertiesList"] });
      // Optionally update the cache directly for better UX
    },
  });
};

export default useAddProperty;
