import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Unit } from "@/types/UnitType";

// The input type omits id, created_at, updated_at, property, as these are usually generated by the backend
export type AddUnitInput = Omit<
  Unit,
  | "id"
  | "created_at"
  | "updated_at"
  | "property"
  | "rooms"
  | "carparks"
  | "meters"
  | "locks"
  | "access_card_numbers"
  | "block_floor_unit_number"
>;

const useAddUnit = () => {
  return useMutation({
    mutationKey: ["AddUnit"],
    mutationFn: async (newUnit: AddUnitInput) => {
      const res = await axiosInstance.post<Unit>("/units", newUnit, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Add unit error:", error);
    },
  });
};

export default useAddUnit;
