import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { PropertyType } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddPropertyInput = Omit<
  PropertyType,
  "id" | "created_at" | "updated_at" | "created_by"
>;

const useAddProperty = () => {
  return useMutation({
    mutationKey: ["AddProperty"],
    mutationFn: async (newProperty: AddPropertyInput) => {
      const res = await axiosInstance.post<PropertyType>(
        "/add-properties",
        newProperty
      );
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Add property error:", error);
    },
  });
};

export default useAddProperty;
