import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import MeterType from "@/types/MeterType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddMeterInput = Omit<
  MeterType,
  | "id"
  | "created_at"
  | "updated_at"
  | "created_by"
  | " meterable_type"
  | "meterable_id"
>;

const useAddMeter = () => {
  return useMutation({
    mutationKey: ["AddMeter"],
    mutationFn: async (newMeter: AddMeterInput) => {
      const res = await axiosInstance.post<MeterType>("/meters", newMeter);
      return res.data;
    },
  });
};

export default useAddMeter;
