import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { UnitType } from "@/types/UnitType";

// The input type omits id, created_at, updated_at, property, as these are usually generated by the backend
export type AddUnitInput = Omit<
  UnitType,
  "id" | "created_at" | "updated_at" | "property"
>;

const useAddUnit = () => {
  return useMutation({
    mutationKey: ["AddUnit"],
    mutationFn: async (newUnit: AddUnitInput) => {
      const res = await axiosInstance.post<UnitType>("/create-units", newUnit);
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Add unit error:", error);
    },
  });
};

export default useAddUnit;
