import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import LockType from "@/types/LockType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddLockInput = Omit<
  LockType,
  "id" | "created_at" | "updated_at" | "created_by"
>;
const useAddLock = () => {
  return useMutation({
    mutationKey: ["AddLock"],
    mutationFn: async (newLock: AddLockInput) => {
      const res = await axiosInstance.post<LockType>("/locks", newLock);
      return res.data;
    },
  });
};

export default useAddLock;
