import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { TenantType } from "@/types/TenantType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddTenantInput = Omit<
  TenantType,
  "id" | "created_at" | "updated_at"
>;

const useAddTenant = () => {
  return useMutation({
    mutationKey: ["AddTenant"],
    mutationFn: async (newTenant: AddTenantInput) => {
      const res = await axiosInstance.post<TenantType>("/tenants", {
        name: newTenant.name,
        email: newTenant.email,
        tenant_profile: newTenant,
      });
      return res.data;
    },
  });
};

export default useAddTenant;
