import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import OwnerType from "@/types/OwnerType";

// Basic owner type - you can update this to match your actual owner structure

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type CreateOwnerInput = Omit<
  OwnerType,
  "id" | "created_at" | "updated_at"
>;

const useCreateOwner = () => {
  return useMutation({
    mutationKey: ["CreateOwner"],
    mutationFn: async (newOwner: CreateOwnerInput) => {
      const res = await axiosInstance.post<OwnerType>("/owners", {
        name: newOwner.name,
        email: newOwner.email,
        owner_profile: newOwner,
      });
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create owner error:", error);
    },
  });
};

export default useCreateOwner;
