import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { TenantType } from "@/types/TenantType";
import BeneficiaryType from "@/types/BeneficiaryType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type CreateBeneficiaryInput = Omit<
  BeneficiaryType,
  "id" | "created_at" | "updated_at"
>;

const useCreateBeneficiary = () => {
  return useMutation({
    mutationKey: ["CreateBeneficiary"],
    mutationFn: async (newBeneficiary: CreateBeneficiaryInput) => {
      const res = await axiosInstance.post("/beneficiaries", {
        name: newBeneficiary.name,
        email: newBeneficiary.email,
        beneficiary_profile: newBeneficiary,
      });
      return res.data;
    },
  });
};

export default useCreateBeneficiary;
