import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateTenancyDocument = (id: number) => {
  return useMutation({
    mutationKey: ["useCreateTenancyDocument"],
    mutationFn: async (data: object) => {
      const res = await axiosInstance.post(`/tenancies/${id}/documents`, data, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
      return res.data;
    },
  });
};

export default useCreateTenancyDocument;
