import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
export type AddPropertyInput = Omit<
  Property,
  "id" | "created_at" | "updated_at" | "created_by"
>;

const useCreateBulkProperty = () => {
  return useMutation({
    mutationKey: ["useCreateBulkProperty"],
    mutationFn: async (newProperty: object[]) => {
      const res = await axiosInstance.post<Property>("/properties/bulk", {
        properties: newProperty,
      });
      return res.data;
    },
  });
};

export default useCreateBulkProperty;
