import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";

// Basic tenancy type - you can update this to match your actual tenancy structure
export type TenancyType = {
  id: number;
  property_name: string;
  tenant_type: string;
  date_of_agreement: string;
  rental_fee: string;
  tenancy_period_start_date: string;
  tenancy_period_end_date: string;
  rental_payment_frequency: string;
  remarks: string | null;
  created_at: string;
  updated_at: string;
};

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
// export type CreateTenancyInput = Omit<
//   TenancyType,
//   "id" | "created_at" | "updated_at"
// >;

const useCreateTenancy = () => {
  return useMutation({
    mutationKey: ["CreateTenancy"],
    mutationFn: async (newTenancy: object) => {
      const res = await axiosInstance.post<TenancyType>(
        "/tenancies",
        newTenancy
      );
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create tenancy error:", error);
    },
  });
};

export default useCreateTenancy;
