import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateBulkBooking = () => {
  return useMutation({
    mutationKey: ["useCreateBulkBooking"],
    mutationFn: async (newProperty: object[]) => {
      const res = await axiosInstance.post("/bookings/bulk", {
        bookings: newProperty,
      });
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create Bulk Booking error:", error);
    },
  });
};

export default useCreateBulkBooking;
