import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";

// Basic owner type - you can update this to match your actual owner structure

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateNewUser = () => {
  return useMutation({
    mutationKey: ["useCreateNewUser"],
    mutationFn: async (newUser: object) => {
      const res = await axiosInstance.post("/admins/users", newUser);
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create New User error:", error);
    },
  });
};

export default useCreateNewUser;
