import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import OwnerType from "@/types/OwnerType";

// Basic owner type - you can update this to match your actual owner structure

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateRole = () => {
  return useMutation({
    mutationKey: ["CreateRole"],
    mutationFn: async (newRole: object) => {
      const res = await axiosInstance.post("/roles", newRole);
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create Role error:", error);
    },
  });
};

export default useCreateRole;
