import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend
const useCreateBooking = () => {
  return useMutation({
    mutationKey: ["useCreateBooking"],
    mutationFn: async (newBooking: object) => {
      const res = await axiosInstance.post<Property>("/bookings", newBooking);
      return res.data;
    },
    onError: (error) => {
      console.error("Create Booking error:", error);
    },
  });
};

export default useCreateBooking;
