import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { TenantType } from "@/types/TenantType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateBeneficiary = () => {
  return useMutation({
    mutationKey: ["CreateBeneficiary"],
    mutationFn: async (newBeneficiary: object) => {
      const res = await axiosInstance.post("/beneficiaries", newBeneficiary);
      return res.data;
    },
  });
};

export default useCreateBeneficiary;
