import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useCreateAgreement = (id: number) => {
  return useMutation({
    mutationKey: ["useCreateAgreement"],
    mutationFn: async (data: object) => {
      const res = await axiosInstance.post<Property>(
        `/tenancies/${id}/agreements`,
        data,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );
      return res.data;
    },
    onError: (error) => {
      console.error("Add property error:", error);
    },
  });
};

export default useCreateAgreement;
