import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useUpdateAvatar = () => {
  return useMutation({
    mutationKey: ["UpdateAvatar"],
    mutationFn: async (data: object) => {
      const res = await axiosInstance.post<Property>(`/profile/avatar`, data, {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
      return res.data;
    },
    onError: (error) => {
      console.error("Add property error:", error);
    },
  });
};

export default useUpdateAvatar;
