import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import OwnerType from "@/types/OwnerType";
import Role from "@/types/RoleType";

// Basic owner type - you can update this to match your actual owner structure

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useUpdateRole = () => {
  return useMutation({
    mutationKey: ["UpdateRole"],
    mutationFn: async (Role: Role) => {
      const res = await axiosInstance.put(`/roles/${Role.id}`, Role);
      return res.data;
    },
    onError: (error) => {
      // Optionally handle error globally
      console.error("Create Role error:", error);
    },
  });
};

export default useUpdateRole;
