import { useMutation } from "@tanstack/react-query";
import axiosInstance from "../ApiCore";
import { Property } from "@/types/PropertyType";

// The input type omits id, created_at, updated_at, as these are usually generated by the backend

const useUpdateProfile = () => {
  return useMutation({
    mutationKey: ["UpdateProfile"],
    mutationFn: async (data: object) => {
      const res = await axiosInstance.put<Property>("/profile", data);
      return res.data;
    },
    onError: (error) => {
      console.error("Update profile error:", error);
    },
  });
};

export default useUpdateProfile;
